### ISSUE TITLE
Track who is the test case writer and who modified last

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#100]
-	We need to be able to track who is creating test cases and when
-	If someone modified a test case than we need to keep both (who created and who last modified)
-	If multiple people modified a test case over time, we are only going to keep the latest modified user info 
-	This information will be shown in test case creation/edit page
-  For this feature to work nicely, we will need to implement the login page.  For now as working around you can just provide drop down for Tester's Name.

**Comment by m3thun** [comment]
@riz-hossain copied, closing
