### ISSUE TITLE
Track who is running/modifying test cases

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#101]
-  We need to keep track of who is running test cases.  For this we only need to keep track of one person. 
- Whoever modified a test case status last, we will keep their name and date and time.
- This information will be shown in run id page and property tab of the test case.
- We need to save this information for per test case basis.
- For now, we will just use the assigned tester’s name.  Once we implement login, we will just take the current logged in user.

**Comment by m3thun** [comment]
@riz-hossain copied, closing
