### ISSUE TITLE
Both manual and automation attachment needs to be implemented via ftp file server

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#105]
We will need to attach files with test cases.  Currently automation execution manages this but needs to be changed how it uploads.  we need to have a ftp type of file server where we can upload any files from any pc (manual or automation).  

There might be some challenge around multiple files, but i think during download we can just zip them all from a specific folder for that test run via run id and download.

**Comment by sazid** [comment]
This won't & shouldn't need a seperate ftp server
