### ISSUE TITLE
Threading for test step expiration 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#116]
- This a target for Version 3.0.  We already have some threading work done but need to organize it better.

- We need to be able to set global level test step time out.  This global value will show up as default value when we are create testing step (they will go to master data like verification)
- If a global value is changed, we need to update all the master data that is using the default value of the global time out.  
- If someone has modified the default value and default value is updated from the global settings (modified test step global setting) then it will keep it unchanged.
- User would have a drop down during test step creation to change the default time out (default time out will be grabbed from the global value and saved in master data)

- When main driver calls the step, it will call the step using the data from master data table of that step.

**Comment by sazid** [comment]
I think, it's either in the works or already done. @riz-hossain @Taitalus respond

**Comment by Taitalus** [comment]
I will work on it after the finishing the test case implementation

**Comment by m3thun** [comment]
@riz-hossain copied, closing
