### ISSUE TITLE
Step order should be modified by mouse movement.

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#128]
A user should be able to drag a step and move a step to change the sequence.

If i have step 
A
B
C 
D

I should be simply drag step D and move to up to second place

A
D
B
C

**Comment by riz-hossain** [comment]
This has not been implemented and will need to be implemented.  Right now I cannot drag drop steps to arrange them.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, January 24, 2015 1:52 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Step order should be modified by mouse movement. (#128)Closed #128.

—Reply to this email directly or view it on GitHub.

**Comment by sazid** [comment]
Yes, it's a duplicate issue. That's why closed it
