### ISSUE TITLE
Some performance test case needs to be created so we can display some information for demo

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#15]
Performance test case needs to be created so we can demo performance graphs

**Comment by riz-hossain** [comment]
We need this open. It won't happen anytime soon. But shouldn't be closed.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, January 24, 2015 1:52 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Some performance test case needs to be created so we can display some information for demo (#15)Closed #15.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain I'm commenting on this because this is the "Oldest Open Ticket" dated back almost 2 years. We need to close the ones that are irrelevant or solved (but not closed). Need to do some maintenance and cleanup. What u say?

**Comment by riz-hossain** [comment]
Actually this was finally completed about 2-3 months ago. So you can actually mark it as done and closed. But we need to seat together and go one by one. It's best that way.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Wednesday, August 19, 2015 12:26 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Some performance test case needs to be created so we can display some information for demo (#15)@riz-hossain I'm commenting on this because this is the "Oldest Open Ticket" dated back almost 2 years. We need to close the ones that are irrelevant or solved (but not closed). Need to do some maintenance and cleanup. What u say?

—Reply to this email directly or view it on GitHub.
