### ISSUE TITLE
Same test case ran more than once in a session does not update result correctly

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#181]
Below run id has two test cases with same test case ran twice.

When i update one of the test case, it updates the same result for other test case.

Additionally, you cannot expand the test case. It will expand and collapse right away

http://135.23.123.67:8080/Home/RunID/Thu-Apr-3-12:07:05-2014/

**Comment by m3thun** [comment]
@riz-hossain copied, closing
