### ISSUE TITLE
Test session runid page needs to collaborate few tabs

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#205]
We need to put 

All, Passed, Failed/Blocked, submitted in one page.  Also put all the other status 
Keep it same concept as rerun

ON rerun page, add ALL button.

We need to put filters like you have on ReRun tab.

However in this case we want a slider  for filters.  Talk with minar to see how he did it.

**Comment by m3thun** [comment]
@riz-hossain copied, closing
