### ISSUE TITLE
Arabic Title Test Case is Failed

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#226]
![arabictestcase](https://cloud.githubusercontent.com/assets/5759182/2743822/f8cec0ba-c71a-11e3-88e7-37ebff935bc2.png)
I have given some title in arabic language.Test Step is creating the test steps successfully.But The test case is not creating successfully.
Eclipse console is showing the following error:
"Exception: 'charmap' codec can't encode characters in position 34-39: character maps to <undefined>"

**Comment by m3thun** [comment]
@riz-hossain copied, closing
