### ISSUE TITLE
Non ASCII Data is not Valid during test case creation

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#227]
![nonascii](https://cloud.githubusercontent.com/assets/5759182/2744092/e286cf46-c71f-11e3-8b18-147bd35cdc88.png)
Non ascii value gives the following error during creation:
"Exception: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>"

**Comment by m3thun** [comment]
@riz-hossain copied, closing
