### ISSUE TITLE
On the progress bar when hovered over, we need to display legend, counts,  and Total

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#249]
- Currently with new changes graph is not working. 
- We actually do not need to show another pie chart.
- We need to display Legend and their count.
- Make sure you give total count

For example:

Vertical Color bar - Pass - 4
Black Vertical Color bar - Total - Total count

**Comment by m3thun** [comment]
@riz-hossain copied and closing
