### ISSUE TITLE
Help system for the site 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#250]
1. We need some kind of help guide for users to explain what are each elements on the page is for. (when help is enabled, all the elements on the page, as soon as you hover over, will show tool tips)
2 We also need to make a separate one that will guide users to create a step or test case or run a test case.  Essentially if you select "Show me how to create a test case", it will take you to create new test case page and ask you to type something in title.  Then it will tell you to select one and so on....(this can be done later)

interactive help Guide:

http://tracelytics.github.io/pageguide/

http://www.jquerypowertour.com/example4.html

http://alvaroveliz.github.io/aSimpleTour/

http://codyhouse.co/gem/product-tour/

http://bootstraptour.com/

**Comment by riz-hossain** [comment]
have a look at these help examples

**Comment by m3thun** [comment]
@riz-hossain copied and closing
