### ISSUE TITLE
Admin page to have option to manage testers

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#251]
- We need to be able to manage testers and their permissions from admin page.  We should be able to add, modify, delete.   We need the following field:

User Name = Must be unique for all users.  As we type this user name, it will display existing user name.  If i select, it will populate all the fields and if its not found, it will create a new user (see below for table info)
Full Name: 
Level: (We should be able to add multiple level.  example: assigned_tester, email, and so on.  the type of level will be stored in the config_value table.  Example type = user_level and value = assigned_tester. we will have drop down option for them to select multiple options)
Email Address:
Password: 

Two tables to store all the data are:
permitted_user_list: this is where a user gets assigned if they are Testers or if they can receive email. 
to add a testers:
user_names = Full Name
user_level = assigned_tester
email = email address

if they have permission to receive email (some people only will have this permission)
user_name = Full Name
user_level = email
email = email address

SECOND TABLE (login)
username = user name (no space and all lower case)
password = user's password
full_name = Full Name

**Comment by m3thun** [comment]
@riz-hossain copied, closing!
