### ISSUE TITLE
Admin link should only be available for admin privileged users 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#255]
Once you finish managing user, we will add a new level called "admin_level_1" and "admin_level_2"

admin_level_1 will be able to perform test case management related task and admin_level_2 will be able to do both level_1 and manage users.

when a user is signed in, we will need to check who is signed in and validate if they are level_1 or level_2.

IF possible, we will only show whatever is their options.

if a non admin user logs in, we should not show the admin option at all.  If level_1 logs in, we will only show level_1 information.

**Comment by m3thun** [comment]
@riz-hossain copied, closing.
