### ISSUE TITLE
Manage Milestone drop down shoud add "Show All"

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#271]
This was again request from end users.  Most users are complaining that not know what are the current available milestone, it is sort of unknown to them.

So we want to add on the drop down "Show All".

When that is selected, we will display a table which will contain information about milestones.

As of now, since we are not really storing too much information we will just show them the list of milestones.  In futures, we will add who created it and modified it last and have option to click from there to take you directly to result page with filtered applied for that milestone.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
