### ISSUE TITLE
View and Organize Steps

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#286]
Once test case view and organize is fully working to spec, We will also implement something similar (it wont be the same) to be able to view all the steps and manage.

We need to be able to batch edit steps settings.  

I will add more detail later.

We may need to put all that under one menu item:

"View & Organize" 
Then user will have a secondary menu

"Test Cases"
"Test Steps"
"Test Set"
and so on ...

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
