### ISSUE TITLE
Task Tracking

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#315]
We need to build a component that will allow us to create and monitor tasks, bugs, requirements.

This is for example a requirement.  

Below are fields that we need.  Since they are very similar with some minor changes, once we do one, it should be very easy to do others.

TASK
Project :(we will need to implement this across all our features include test cases)
Team:  Each project can have multiple teams
Component:  This will be  a drop down.  It is more like sections. 
ID: Should be first 4 letters of the project name and numbers
Title,
Body:
Comments: Others will be able to add comments (it should show, who commented, time stamp, how many days/weeks ago)
Start Date: (should be a date picker from a calendar)
End Date: (date picker)
Time Remaining:
Created By:
Assigned To:
Priority:
Milestone:
Reminder: Which day to send notification to 
Status: Not started, Started, Completed, Over Due flag
Tags: User should be able to manage tags like git hub as well
Related Items: Should be able to add other tasks, requirements, or bug
Monitors: add other users who will get notification about any new comments or change of status is made.
Trace: show history of the status.  If it was assigned from one person to another we need to show those info.  A date.  And show fields that were changed

I will have to explain one more feature to see how we can group multiple tasks under one.  Plan is to be able to have a parent tasks and have child tasks below.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
