### ISSUE TITLE
Implement Select2 api for all the search area

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#317]
There are multiple options, but we want the one shown in the screen capture below.  The searched item will be stored inside the search box. 

There is another feature where we can limit user to at least enter 1 or 2 letters.  We may implement that for areas that we expect to see large number of data.

http://ivaynberg.github.io/select2/

Start with copy/edit test case section.  

two critical features here are that we want to automatically display content and group the categories.  

![image](https://cloud.githubusercontent.com/assets/5302523/3240305/4ab0cda0-f124-11e3-85a2-ccc7052833a6.png)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
