### ISSUE TITLE
Test case searching by labels

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#332]

**Comment by sazid** [comment]
Needs attention @riz-hossain

**Comment by riz-hossain** [comment]
Currently I cannot search test cases by label. Any places that allows me to search test cases by categories, I should be able to search by label as well.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, January 24, 2015 1:47 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test case searching by labels (#332)Needs attention @riz-hossain 

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
