### ISSUE TITLE
Drivers should be able to map step name to function automatically

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#340]
Main driver should automatically map the function name with step name (dynamically).

The logic we will use is that when someone makes a function in their driver, they will have to name the function same as the step name with _ instead of space.  When we we get the step, we will simply replace all the spaces with _ and construct the function name/link directly.

Here is an example of how you can take a sting and construct an object/function out of it...
Obj = BB.API # instantiate some object
# Strg = “.OpenContact()”
Strg = "OpenContact" # string should be just method name
Api_call = Obj.getattr(Strg) # get method from object by name
Api_call() # call the method!
# or, you don't have to put it into a separate variable:
Obj.getattr(Strg)() # call the method

This will eliminate the need for manual step to function name mapping... and make life a lot more smoother...

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
