### ISSUE TITLE
run manager service needs ui

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#341]
Currently run manager is a python file that we run.. that runs as cmd window. 

We need to make it an application type..  it will have similar functionality ...

there are new condition that went into run manager now.  Once shetu fixes the runmanager, you will essentially take the same activity and make it into UI.  it doesnt have to be any fancy ui.. twinker can be used for it. 

First the app will ask for user and password .. 
then they will be given option to select project and then team...

Once that is done, based on your project's and team's dependency, we will need to run some functions if available .. i will talk about it more in detail later .. you can just call a dummy function for now...

We will add some other functions to the ui in future.. for now these are must for automation to run 

@Taitalus  please complete the fixes asap for automation .... we need the automation up and running for our new clients..

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
