### ISSUE TITLE
various string or Boolean values should be accepted  by main driver 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#342]
When sub drivers sends the result of individual steps, main driver should be able to accept various string or boolean values.

Example:
Results taken as pass can be:

Pass, pass, True (boolean or string), Passed, Success, success, .. and if you can think of any other logical value ..

opposite also applies for failed cases...

**Comment by Taitalus** [comment]
Done

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
