### ISSUE TITLE
Creating new task saving data but not showing in edit view

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#345]

**Comment by sazid** [comment]
But, it's showing, on my side. Look at the gif
![task create](https://cloud.githubusercontent.com/assets/2370167/5886307/11b524fa-a3c2-11e4-946e-6b30929b9236.gif)

**Comment by sazid** [comment]
@riz-hossain

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
