### ISSUE TITLE
buttons are not aligned properly

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#347]
http://demo.automationsolutionz.com/Home/RunID/Sun-Jan-18-10:11:46-2015/TC/CRE-0369/View/

in this case, i think its best if we do not use the new auto resize of the column.  here most of the user would want to see full detail.  

in my tablet the buttons are over lapped.

**Comment by minar09** [comment]
Created two CSS classes as 'one-column-emphasis' and 'two-column-emphasis'. If any table has text boxes or buttons which got disproportion, use 'two-column-emphasis' css class to use as normal table. And 'one-column-emphasis' class is for truncating table string in case of long text.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
