### ISSUE TITLE
Run Id Detail page Pagination

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#348]
along with the status and comment modification in the manual test case execution view page and verification point on those pages

**Comment by sazid** [comment]
Isn't it already done? @Taitalus

**Comment by riz-hossain** [comment]
No. Pagination needs to be done on every page that displays test cases.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, January 24, 2015 1:23 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Run Id Detail page Pagination (#348)Isn't it already done? @Taitalus 

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
