### ISSUE TITLE
Unable to edit test case

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#349]
Getting message "Exception: local variable 'result' referenced before assignment"

**Comment by minar09** [comment]
Working for other test cases :/

**Comment by sazid** [comment]
@minar09 maybe, the test case was corrupted.

**Comment by minar09** [comment]
yeah, closed it.

**Comment by minar09** [comment]
Is it only me who is having this issue more often while editing a test case after creation?

**Comment by riz-hossain** [comment]
Edit test case a lot of time doesn't load data. And once you save it with bad data, you can never save that test case again. I think that's one of the bug I logged.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Friday, January 23, 2015 6:27 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Unable to edit test case (#349)Is it only me who is having this issue more often while editing a test case after creation?

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
I am facing this for almost every cases now.

On Sat, Jan 24, 2015 at 6:19 AM, Riz Hossain <notifications@github.com>
wrote:

> Edit test case a lot of time doesn't load data. And once you save it with
> bad data, you can never save that test case again. I think that's one of
> the bug I logged.
> Sent from my BlackBerry 10 smartphone on the TELUS network. From: Matiur
> Rahman MinarSent: Friday, January 23, 2015 6:27 PMTo:
> AutomationSolutionz/Framework_0.1Reply To:
> AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Unable to
> edit test case (#349)Is it only me who is having this issue more often
> while editing a test case after creation?
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/349#issuecomment-71289132>
> .
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.

**Comment by riz-hossain** [comment]
Don't reset your db and work with shetu to fix this issue.  This is the most critical issue.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Friday, January 23, 2015 7:22 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Unable to edit test case (#349)I am facing this for almost every cases now.



On Sat, Jan 24, 2015 at 6:19 AM, Riz Hossain <notifications@github.com>

wrote:



> Edit test case a lot of time doesn't load data. And once you save it with

> bad data, you can never save that test case again. I think that's one of

> the bug I logged.

> Sent from my BlackBerry 10 smartphone on the TELUS network. From: Matiur

> Rahman MinarSent: Friday, January 23, 2015 6:27 PMTo:

> AutomationSolutionz/Framework_0.1Reply To:

> AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Unable to

> edit test case (#349)Is it only me who is having this issue more often

> while editing a test case after creation?

>

> —Reply to this email directly or view it on GitHub.

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/AutomationSolutionz/Framework_0.1/issues/349#issuecomment-71289132>

> .

>







-- 

Matiur Rahman Minar

Programmer

Automation Solutionz

1212 Countrystone Drive,

Kitchener, N2N 3R4.

—Reply to this email directly or view it on GitHub.

**Comment by sazid** [comment]
```python
"Exception: local variable 'result' referenced before assignment"
```
That error message explains everything. I've seen some of those variable assignments before, somewhere. Basically, it should be a one/two line fix if there's no other logic during variable assignment.

**Comment by Taitalus** [comment]
Don't worry. It will be sort soon. working on the keyfield and the ignore field .Then I will work on edit altogether.

**Comment by Taitalus** [comment]
Working nicely now.
