### ISSUE TITLE
Test case creation page Toggle Button

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#350]
It showed nicely during creation . but only showing half filled in the edit page. Told @minar09  to see this . He agreed. Here is a snap .
![taskpage](https://cloud.githubusercontent.com/assets/5759182/5873261/b3bd2684-a31e-11e4-8896-67e301a51bc3.png)

**Comment by Taitalus** [comment]
@riz-hossain vai I have assigned this to @minar09 . Hope it's alright.

**Comment by sazid** [comment]
Small screen
-------

![capture](https://cloud.githubusercontent.com/assets/2370167/5873508/895ac128-a321-11e4-8a4c-4bdf903cbbd3.PNG)

**Comment by m3thun** [comment]
@riz-hossain Copied and Closing!
