### ISSUE TITLE
Test Case Feature in Edit Test Case Page

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#352]
In database the feature is save correctly. but don't show up properly in the edit page. 
For example someone select First.Third.Fifth in the feature but it only shows First.Fifth in the edit page.
I have checked in the database. nothing wrong with the saving. 
As This was implemented by @minar09 .I am assigning this to him. 
@riz-hossain  please look into this matter.

**Comment by sazid** [comment]
Hmm, it's been a long-time known bug. I've also checked everything. Even the data is being returned correctly. But, due to some UI logic, the latter one replaces the former one and takes its place. But, the data is still there. Whoever did this, should be a quick fix for him.

**Comment by Taitalus** [comment]
Yeah.

**Comment by minar09** [comment]
Actually I didn't do any extra code for showing feature rather i just
replaced codes for showing section with features' in the same way.

On Sat, Jan 24, 2015 at 11:48 AM, Raju Ahmed Shetu <notifications@github.com
> wrote:

> Yeah.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/352#issuecomment-71301745>
> .
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.

**Comment by riz-hossain** [comment]
I want everyone to look into it as no one has found a solution yet.I have talked about this bug for many times. If it is the ui, then change the ui flow if you can't fix it with current ui.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Saturday, January 24, 2015 6:13 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test Case Feature in Edit Test Case Page (#352)Actually I didn't do any extra code for showing feature rather i just

replaced codes for showing section with features' in the same way.



On Sat, Jan 24, 2015 at 11:48 AM, Raju Ahmed Shetu <notifications@github.com

> wrote:



> Yeah.

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/AutomationSolutionz/Framework_0.1/issues/352#issuecomment-71301745>

> .

>







-- 

Matiur Rahman Minar

Programmer

Automation Solutionz

1212 Countrystone Drive,

Kitchener, N2N 3R4.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
