### ISSUE TITLE
Info for Test Case step name and data in Detail Tab

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#360]
It will be done in the Detail Tab. There will be a button namely Show Format clicking on which it will show the step name and step data in tabular format. Also dependency is to be shown. 

@raqbo  and @riz-hossain  which one I should do first , this one or #359 ??

**Comment by riz-hossain** [comment]
Button name may need to be changed later...For now put Data Format                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Monday, February 2, 2015 11:37 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: [Framework_0.1] Info for Test Case step name and data in Detail Tab (#360)It will be done in the Detail Tab. There will be a button namely Show Format clicking on which it will show the step name and step data in tabular format. Also dependency is to be shown. 

@raqbo  and @riz-hossain  which one I should do first , this one or #359 ??

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
so I am doing this one first okay??

**Comment by riz-hossain** [comment]
Yes.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Monday, February 2, 2015 11:49 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Info for Test Case step name and data in Detail Tab (#360)so I am doing this one first okay??

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
fInished fully. @raqbo  and @riz-hossain please see this.. and close this..
