### ISSUE TITLE
Issues with project settings 

### ISSUE THREAD

**Issue by m3thun** [AutomationSolutionz/Framework_0.1#361]
@Taitalus can you make sure these old bugs are not there in new design? 

(1)​ When I'm in "Manage -> Project Settings -> Feature" tab, here's what happened:

  (i) I tried to create a feature called mitFeature_1, it was created successfully.
 
 (ii) I tried to create a feature called "mit,Feature" (intentionally putting a comma in the name), neither did it give me an error, nor it created the feature. It simply did nothing. An error message should be displayed suggesting the criteria of naming (only Alphanumeric etc..).

  (iii) Similarly, I tried to create "mitFeature2." and "mitFeature2@", nothing happens.

  (iv) I tried to delete the Features I've created, it does NOT delete.

  (v) I created a Feature called "m.i.t", it created the Feature with the name "m". So anything after the dot (.) is ignored but still accepts such name.

  (vi) I created a Feature named "R.i.z", just like last time it saved the name as "R". This time I created another feature named "R.i.z.u", nothing happens. So, I tried adding "R.i.z.u" again, now it says the name already exists.

So, basically if someone adds R.i.z / R.i.z.u / R.i.z.w.a.n, all 3 features will be added in the database, but only one name "R" will be displayed.

(vii) After creating a Feature, the page auto-refreshes, and goes back to first tab, which is "Dependency". Then again I've to click the Feature tab to get there. If I'm in Feature tab, even after the page refreshes, it should bring me back to the same tab.

(viii) I tried to Link / Unlink Features, both actions worked fine.

(2) Under "Requirement -> Create/Edit", while choosing a Feature from the drop-down menu, it would be convenient for the user if a "Create New.." option is added, which would take the user directly to "Manage -> Project Settings". It would be convenient if there are currently no features and the list is empty. so the user can just click and immediately go to the page where one could be created.

This will minimize the number of times the user has to go back and forth between Menus.

**Comment by minar09** [comment]
Features are saved in postgresql ltree format e.g.
First.second.third.fourth etc. That's why i guess only the text before
dot(.) is shown. So it should be prevented in front-end not to put dot(.)
in feature name.

On Tue, Feb 3, 2015 at 12:04 PM, m3thun <notifications@github.com> wrote:

> (1)​ When I'm in "Manage -> Project Settings -> Feature" tab, here's what
> happened:
>
> (i) I tried to create a feature called mitFeature_1, it was created
> successfully.
>
> (ii) I tried to create a feature called "mit,Feature" (intentionally
> putting a comma in the name), neither did it give me an error, nor it
> created the feature. It simply did nothing. An error message should be
> displayed suggesting the criteria of naming (only Alphanumeric etc..).
>
> (iii) Similarly, I tried to create "mitFeature2." and "mitFeature2@",
> nothing happens.
>
> (iv) I tried to delete the Features I've created, it does NOT delete.
>
> (v) I created a Feature called "m.i.t", it created the Feature with the
> name "m". So anything after the dot (.) is ignored but still accepts such
> name.
>
> (vi) I created a Feature named "R.i.z", just like last time it saved the
> name as "R". This time I created another feature named "R.i.z.u", nothing
> happens. So, I tried adding "R.i.z.u" again, now it says the name already
> exists.
>
> So, basically if someone adds R.i.z / R.i.z.u / R.i.z.w.a.n, all 3
> features will be added in the database, but only one name "R" will be
> displayed.
>
> (vii) After creating a Feature, the page auto-refreshes, and goes back to
> first tab, which is "Dependency". Then again I've to click the Feature tab
> to get there. If I'm in Feature tab, even after the page refreshes, it
> should bring me back to the same tab.
>
> (viii) I tried to Link / Unlink Features, both actions worked fine.
>
> (2) Under "Requirement -> Create/Edit", while choosing a Feature from the
> drop-down menu, it would be convenient for the user if a "Create New.."
> option is added, which would take the user directly to "Manage -> Project
> Settings". It would be convenient if there are currently no features and
> the list is empty. so the user can just click and immediately go to the
> page where one could be created.
>
> This will minimize the number of times the user has to go back and forth
> between Menus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/361>.
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.

**Comment by sazid** [comment]
`"first.second.third.fourth.fifth".split('.')` should do inshaAllah. Since, it'll be readily converted into an array, the result can be directly used to populate the UI elements.

**Comment by riz-hossain** [comment]
We need to figure out if with all this bug it's worth fixing them or redoing. Sazid, you haven't fixed the multiple pop up issues and explained that it was too hard. Can you suggest if this is fixable and what needs to be done. Or shetu has to redo the code.  This need to be fixed asap.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: m3thunSent: Tuesday, February 3, 2015 1:04 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Issues with "Feature" (#361)(1)​ When I'm in "Manage -> Project Settings -> Feature" tab, here's what happened:

(i) I tried to create a feature called mitFeature_1, it was created successfully.

(ii) I tried to create a feature called "mit,Feature" (intentionally putting a comma in the name), neither did it give me an error, nor it created the feature. It simply did nothing. An error message should be displayed suggesting the criteria of naming (only Alphanumeric etc..).

(iii) Similarly, I tried to create "mitFeature2." and "mitFeature2@", nothing happens.

(iv) I tried to delete the Features I've created, it does NOT delete.

(v) I created a Feature called "m.i.t", it created the Feature with the name "m". So anything after the dot (.) is ignored but still accepts such name.

(vi) I created a Feature named "R.i.z", just like last time it saved the name as "R". This time I created another feature named "R.i.z.u", nothing happens. So, I tried adding "R.i.z.u" again, now it says the name already exists.

So, basically if someone adds R.i.z / R.i.z.u / R.i.z.w.a.n, all 3 features will be added in the database, but only one name "R" will be displayed.

(vii) After creating a Feature, the page auto-refreshes, and goes back to first tab, which is "Dependency". Then again I've to click the Feature tab to get there. If I'm in Feature tab, even after the page refreshes, it should bring me back to the same tab.

(viii) I tried to Link / Unlink Features, both actions worked fine.

(2) Under "Requirement -> Create/Edit", while choosing a Feature from the drop-down menu, it would be convenient for the user if a "Create New.." option is added, which would take the user directly to "Manage -> Project Settings". It would be convenient if there are currently no features and the list is empty. so the user can just click and immediately go to the page where one could be created.

This will minimize the number of times the user has to go back and forth between Menus.

—Reply to this email directly or view it on GitHub.

**Comment by sazid** [comment]
I was talking about dot thing. But, the page, if redone is better in my opinion. 

http://ignitersworld.com/lab/contextMenu.html

**Comment by riz-hossain** [comment]
For dot, Mithun wants dot in his string. We cannot allow that. So we need to block users from submitting anything with . in their string for any places that we have tree.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Tuesday, February 3, 2015 8:20 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Issues with "Feature" (#361)I was talking about dot thing. But, the page, if redone is better in my opinion. 

http://ignitersworld.com/lab/contextMenu.html

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
