### ISSUE TITLE
Finishing the UI Admin

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#368]
Here goes the requirement:
1. Manage Project options will be there. On clicking those it will open an interface just like the set and tag.

2.List project option will be there. 
Clicking on those will open a table containing all these information
a. Project Name 
b. Owner
c. Start Date 
d. End Date
e. Team

3. Team Owner Can be changed. 

@raqbo  and @riz-hossain  please approve the requirements . I will start work after that.

**Comment by Taitalus** [comment]
@riz-hossain  vai please confirm this.

**Comment by riz-hossain** [comment]
Hmm please refer to the discussion we had in Dhaka. Look at your notes and make sure everything is covered. Additionally add a new field where you will add hours available in a day and days available in a week for each user. We will be using this later for planning.  so two additional fields.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 5, 2015 11:57 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Finishing the UI Admin (#368)@riz-hossain  vai please confirm this. 

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
