### ISSUE TITLE
Edit Type Data Passing in Main Driver

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#369]
Previously we are able to send single and multiple dataset from maindriver to any other driver file. Now we want to send the edit type data. 
We can create test case by edit type data. now we want to do pass the data from maindriver and show them into execution page.

**Comment by Taitalus** [comment]
@riz-hossain  and @raqbo  please see this.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
