### ISSUE TITLE
data from main drivers are being sent in random orders

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#378]
when data are are coming from main driver to step, they are not coming in the order that is entered in the test case.

**Comment by Taitalus** [comment]
done as like as the test case edit page.

**Comment by riz-hossain** [comment]
It is showing in the execution data in reverse order so i am sure main driver will be wrong ..

the bug is not in the main driver.. the bug is when you are copying the data from master table to execution table.


![image](https://cloud.githubusercontent.com/assets/5302523/6119334/6abd39a4-b095-11e4-96ad-16c6aa1d8a62.png)

**Comment by riz-hossain** [comment]
![image](https://cloud.githubusercontent.com/assets/5302523/6119356/c1d1f75c-b095-11e4-9f96-0808bc3c9deb.png)

**Comment by Taitalus** [comment]
I fixed that for main driver.for this page it is to be fixed.

**Comment by Taitalus** [comment]
Main Drivers are being sequenced now.
