### ISSUE TITLE
in correct status is displayed.  Even when module is passing it is displaying error.

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#379]
![image](https://cloud.githubusercontent.com/assets/5302523/6097950/445493b4-af9d-11e4-9195-f452d7c0ed32.png)
http://demo.automationsolutionz.com/Home/RunID/Sun-Feb-8-14:14:55-2015/

**Comment by Taitalus** [comment]
This is happening whoever wrote the driver file gives the LogLevel = 1. That is not a database problem rather it is  a developer's problem. 

CommonUtil.ExecLog(sModuleInfo, sDetails, iLogLevel=1) that is the definition.

iLogLevel:
1=PASSED
2=WARNING
3=FAILED
