### ISSUE TITLE
Only test set created for the project and team should display 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#385]

**Comment by minar09** [comment]
It seems it needs DB modification. Right now set and tags are simply being saved in config_values table.

**Comment by riz-hossain** [comment]
If it has id, we can use the team wise setting table. So we put the id mapping there and then we can use that to filter.  But if we need to add, sure. If we need to add it sure. Please make sure we add other info such as who created and when and last modified date.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Thursday, February 12, 2015 10:30 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Only test set created for the project and team should display  (#385)It seems it needs DB modification. Right now set and tags are simply being saved in config_values table.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
New Test set creation is now linked with project and team, and only project-team wise sets will be shown.

**Comment by riz-hossain** [comment]
I cannot seem to create any new test set.

I dont know if there is any new db thats needed for this .. if there is ..
please upload . if not please fix the issue

On Thu, Feb 12, 2015 at 4:49 PM, Matiur Rahman Minar <
notifications@github.com> wrote:

> New Test set creation is now linked with project and team, and only
> project-team wise sets will be shown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/385#issuecomment-74160332>
> .
>



-- 

Riz Hossain
Engineering Physics (B.Eng)
Automation Test Lead
Research In Motion
295 Phillip Street
Waterloo, ON N2L 3L3


This transmission (including any attachments) may contain confidential
information, privileged material (including material protected by the
solicitor-client or other applicable privileges), or constitute non-public
information. Any use of this information by anyone other than the intended
recipient is prohibited. If you have received this transmission in error,
please immediately reply to the sender and delete this information from
your system. Use, dissemination, distribution, or reproduction of this
transmission by unintended recipients is not authorized and may be unlawful.

**Comment by minar09** [comment]
No new db is needed. Just team_wise_settings table is used. Or maybe there is not set is shown, that's why you cannot create as you said.

**Comment by minar09** [comment]
Fixed in new commit.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
