### ISSUE TITLE
view and organize page is not displaying any test cases

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#386]
whatever new changes were made is breaking the view and organize page

**Comment by minar09** [comment]
Fixed this page as the test set page, similar bug.

**Comment by riz-hossain** [comment]
Nice. Can you make sure you can create new section. Should be working but just to double check.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Thursday, February 12, 2015 5:25 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] view and organize page is not displaying any test cases (#386)Fixed this page as the test set page, similar bug.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
Yeah. Working. Tested with creating test cases.
