### ISSUE TITLE
Test case search for deployment should be project and team wise

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#387]
Test case search for deployment should be project and team wise, otherwise its making messes in reports as report is done based on particular project and team.

**Comment by minar09** [comment]
@riz-hossain  vai, this needs getting done before jumping to a clean DB.

**Comment by riz-hossain** [comment]
Is this a lengthy fix?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Wednesday, February 11, 2015 2:31 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test case search for deployment should be project and team wise (#387)@riz-hossain  vai, this needs getting done before jumping to a clean DB.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
I am quite sure about deployment search.

**Comment by minar09** [comment]
I am not quite sure about that.

**Comment by Taitalus** [comment]
Already done. Check.                                                                                                                                                                                                                                                                          Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Thursday, February 12, 2015 1:32 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Test case search for deployment should be project and team wise (#387)                                                                                      Is this a lengthy fix?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Wednesday, February 11, 2015 2:31 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test case search for deployment should be project and team wise (#387)@riz-hossain  vai, this needs getting done before jumping to a clean DB.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and done!
