### ISSUE TITLE
Search test case is not able to display any test caae

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#389]
I cannot search any test cases from test case search feature

**Comment by Taitalus** [comment]
pagination is needed in this page.

**Comment by riz-hossain** [comment]
For pagination, please create a new ticket.  Also this page by default should show all test cases.  The filters will reduce the test case search. Same as result page for test case how we show all runs and one can reduce them by applying filters. Please do these as well if you can finish them quickly.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Wednesday, February 11, 2015 11:41 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Search test case is not able to display any test caae (#389)pagination is needed in this page.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
In this page pagination was the main issue. Because TableDataTestCasesOtherPages needed two parameter called test_case_page_current and test_case_per_page which was absent in this page. .It's now fixed.
