### ISSUE TITLE
Unable to add new test cases to test set 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#390]
In test set page, when I select a test set to add test cases, it doesn't display any test cases.

**Comment by minar09** [comment]
The reason behind the regression is the parameter and functional change of the test cases fetching function. Since the same function was modified for pagination in another page, and this page was not updated so, that made the bug. Now this is also updated with pagination.

**Comment by riz-hossain** [comment]
In that case view and organize may also be solved.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Thursday, February 12, 2015 4:11 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Unable to add new test cases to test set  (#390)The reason behind the regression is the parameter and functional change of the test cases fetching function. Since the same function was modified for pagination in another page, and this page was not updated so, that made the bug. Now this is also updated with pagination.

—Reply to this email directly or view it on GitHub.
