### ISSUE TITLE
Every Search Box is to have the test case title autosuggestion feature.

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#395]

**Comment by riz-hossain** [comment]
same drop box as test case and test step creation page ..

this bug is applied to deployment page search boxes.

Search test case 
detail tab search boxes (except dates, and objective all other boxes needs it)

**Comment by Taitalus** [comment]
Sorry The first tab test cases search is left.

**Comment by riz-hossain** [comment]
Keep in mind to display search content based on current proejct and team. Right now it's displaying everything from all projects.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 12, 2015 4:00 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Every Search Box is to have the test case title autosuggestion feature. (#395)Sorry The first tab test cases search is left.

—Reply to this email directly or view it on GitHub.
