### ISSUE TITLE
Drop down for deployment, search test case are not displaying content based on proejct and team

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#402]
Drop down selection content needs to show based on team and project

**Comment by Taitalus** [comment]
it's displaying . and always filters with project and team.  see there the condition of the db
![no problem in db](https://cloud.githubusercontent.com/assets/5759182/6187370/d3fc2318-b3af-11e4-9a23-499954e9bd74.png)

**Comment by riz-hossain** [comment]
There is a double mapping for section.  I'm this table there is no team or project mapping. That table should only be looked at for when creating section.  You need to look at team wise settings table                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 7:41 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)it's displaying . and always filters with project and team.  see there the condition of the db


—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Or we can add two more columns here... Project id and team id. Then it may make life a lot easier.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:55 AMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There is a double mapping for section.  I'm this table there is no team or project mapping. That table should only be looked at for when creating section.  You need to look at team wise settings table                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 7:41 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)it's displaying . and always filters with project and team.  see there the condition of the db


—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Also... keep in mind that in the tag table when we split these sections, they all need to refer back to team and project as well.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:58 AMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      Or we can add two more columns here... Project id and team id. Then it may make life a lot easier.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:55 AMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There is a double mapping for section.  I'm this table there is no team or project mapping. That table should only be looked at for when creating section.  You need to look at team wise settings table                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 7:41 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)it's displaying . and always filters with project and team.  see there the condition of the db


—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

**Comment by riz-hossain** [comment]
There must be something wrong with the query. You maybe getting the section id properly. But android section does not belong to project 29. Also keep in mind that at the end we split all the sections and put them independently in the test case tag table. If there is something wrong with db. Make the changes needed and show me that android section does not show up in this project but shows up in project 19.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:02 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
I think this project supposed to have one folder only named 'Clicksafety' right?? Adjusting db. We added those section to test..                                                                                                                                                                                                                                                                           Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:11 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There must be something wrong with the query. You maybe getting the section id properly. But android section does not belong to project 29. Also keep in mind that at the end we split all the sections and put them independently in the test case tag table. If there is something wrong with db. Make the changes needed and show me that android section does not show up in this project but shows up in project 19.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:02 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
When I go to manage test cases, I don't see android section there.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:15 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I think this project supposed to have one folder only named 'Clicksafety' right?? Adjusting db. We added those section to test..                                                                                                                                                                                                                                                                           Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:11 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There must be something wrong with the query. You maybe getting the section id properly. But android section does not belong to project 29. Also keep in mind that at the end we split all the sections and put them independently in the test case tag table. If there is something wrong with db. Make the changes needed and show me that android section does not show up in this project but shows up in project 19.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:02 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Don't remove all the sections from all projects.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 8:21 AMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      When I go to manage test cases, I don't see android section there.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:15 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I think this project supposed to have one folder only named 'Clicksafety' right?? Adjusting db. We added those section to test..                                                                                                                                                                                                                                                                           Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:11 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There must be something wrong with the query. You maybe getting the section id properly. But android section does not belong to project 29. Also keep in mind that at the end we split all the sections and put them independently in the test case tag table. If there is something wrong with db. Make the changes needed and show me that android section does not show up in this project but shows up in project 19.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:02 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
View and organize I meant to say                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 8:21 AMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      When I go to manage test cases, I don't see android section there.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:15 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I think this project supposed to have one folder only named 'Clicksafety' right?? Adjusting db. We added those section to test..                                                                                                                                                                                                                                                                           Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Friday, February 13, 2015 7:11 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)                                                                                      There must be something wrong with the query. You maybe getting the section id properly. But android section does not belong to project 29. Also keep in mind that at the end we split all the sections and put them independently in the test case tag table. If there is something wrong with db. Make the changes needed and show me that android section does not show up in this project but shows up in project 19.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 13, 2015 8:02 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Drop down for deployment, search test case are not displaying content based on proejct and team (#402)I have got this info after running a query joining the team_wise_settings and product_sections. Here it is giving the section that are associated with the team 152(WebAutomation) and project PROJ-29(Automation). see the query.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
‎Shetu,Please look into this issue.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: chandanghosh21Sent: Monday, February 23, 2015 11:54 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Unable to create a Test case  (#439)URL: http://demo.automationsolutionz.com/Home/Login/


Go to the above URL
Login with valid credential
Try to create a test case


Please see the attachment.


Expected result: Test case should create
Actual Result: Unable to create a test case.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
