### ISSUE TITLE
Result and execution page filter needs updated drop down 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#403]

**Comment by Taitalus** [comment]
nothing is wrong. drop down is updated and it's filtering with team and projects always. That's in the db.see.
![no problem in db](https://cloud.githubusercontent.com/assets/5759182/6187355/a8d48194-b3af-11e4-904d-516ec9b803fd.png)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
