### ISSUE TITLE
MainDriver is running a test case twie.

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#414]

**Comment by riz-hossain** [comment]
You can mark it done                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, February 15, 2015 2:20 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] MainDriver is running a test case twie. (#414)

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
You solved??                                                                                                                                                                                                                                                                           Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Sunday, February 15, 2015 1:46 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] MainDriver is running a test case twie. (#414)                                                                                      You can mark it done                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, February 15, 2015 2:20 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] MainDriver is running a test case twie. (#414)

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
closing..
