### ISSUE TITLE
Option to restore test cases from old run. 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#418]
Since we are are still having permanent data loses of test cases by editing them, we need to give users option to restore test cases from old test cases from executed test run. This will work more like a restore feature.  

All data for that cases gets backed up in our execution tables. We need to have a feature that says "restore from previous versions" 

Once clicked, it will display multiple versions from the previous runs. Once users selects one, it will delete the current test cases content and restore all steps and data from the old runid.  

If we don't want to give any option to select versions , we simply take the test case data of the last run history and restore it.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
