### ISSUE TITLE
Test Case Attachment is done

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#425]

**Comment by riz-hossain** [comment]
Is it tested?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:02 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Test Case Attachment is done (#425)

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
List the test cases please                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Riz HossainSent: Thursday, February 19, 2015 12:12 PMTo: Raju Ahmed Shetu; AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Test Case Attachment is done (#425)                                                                                      Is it tested?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:02 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Test Case Attachment is done (#425)

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
Yes vai.                                                                                                                                                                                                                                                                          Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Thursday, February 19, 2015 11:12 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] Test Case Attachment is done (#425)                                                                                      Is it tested?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:02 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Test Case Attachment is done (#425)

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
List the test cases?? please elaborate.

**Comment by riz-hossain** [comment]
How and what did you test.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:13 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test Case Attachment is done (#425)List the test cases?? please elaborate.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
ow. okay.

Test Cases:
1. I have attached an xls file.
2. then attached image file
3. attached an pdf.
Result:
1.I was able to download xls file. 
2.The attached image was viewed correctly
3.I was able to download the pdf file.

**Comment by riz-hossain** [comment]
How about in result page. No one will be downloading it from edit view.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:17 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test Case Attachment is done (#425)ow. okay.

Test Cases:
1. I have attached an xls file.
2. then attached image file
3. attached an pdf.
Result:
1.I was able to download xls file. 
2.The attached image was viewed correctly
3.I was able to download the pdf file.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
you told me to do that like this.

**Comment by riz-hossain** [comment]
Yes to upload. But it's no good if users can't view them during run.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:21 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test Case Attachment is done (#425)you told me to do that like this.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
so what should we do then?? 
I will give them option to view from the run page.

**Comment by riz-hossain** [comment]
Yes. Also test:Upload attachments to old test cases that didn't have attachment Upload same attachment to different test steps  of the same test case Deleted attachments from existing test cases What type of limit do we have?   Can I upload 700mb file? We should probably limit to 5mb.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, February 19, 2015 12:24 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test Case Attachment is done (#425)so what should we do then?? 
I will give them option to view from the run page.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
can't understand vai.

**Comment by riz-hossain** [comment]
when attachment is added to the exuection/view page, then you can tag it as Done
