### ISSUE TITLE
Status in the manual machine is to be shown correctly

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#430]

**Comment by Taitalus** [comment]
I have fixed that right now. But what you wanted needs another separate module or python process to constantly look over the database to inspect the status change of machines. I guess the day before demo is not the right time to do it. I will create a tab on it. and tag it as done.

**Comment by riz-hossain** [comment]
We already have a separate process that mina‎r created for email. However you don't need it. We only need to check for this when someone clicks on deployment link. When deployment link is clicked, we can do the clean up. Let's do this after demo.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Friday, February 20, 2015 2:11 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Status in the manual machine is to be shown correctly (#430)I have fixed that right now. But what you wanted needs another separate module or python process to constantly look over the database to inspect the status change of machines. I guess the day before demo is not the right time to do it. I will create a tab on it. and tag it as done. 

—Reply to this email directly or view it on GitHub.
