### ISSUE TITLE
This warning from main driver needs to be removed.  It is not relevant content

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#438]
![image](https://cloud.githubusercontent.com/assets/5302523/6317078/cc1fd936-ba0e-11e4-9ed0-94df7ef5a6f9.png)

**Comment by sazid** [comment]
Well, it's a programming error. Besides, how come errors or warmings show
up in the results? There's probably a fault in the logic

**Comment by riz-hossain** [comment]
A warning level log doesn't fail test cases, but an error fails a test case. Main driver needs to log messages to server. There are different log levels and other logics that you need to review.  If main driver is calling a step and which driver and such those information needs to be shown in the web.  But this is what we decide to show in db result, so we are in control of it. There is option to just write to our local log and not show in web. This one is the one that we need write to local log so that if something goes wrong we can debug from framework point of view. This maybe expected and such or we may have closed the connection before and we are trying to close again. It's not gonna harm anything but it shouldn't show up as test case execution log. ‎ But main point is this shouldn't be a warning level 2 log but log level 4.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, February 21, 2015 11:14 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] This warning from main driver needs to be removed.  It is not relevant content (#438)Well, it's a programming error. Besides, how come errors or warmings show
up in the results? There's probably a fault in the logic

On Sun, Feb 22, 2015, 8:38 AM Riz Hossain <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/5302523/6317078/cc1fd936-ba0e-11e4-9ed0-94df7ef5a6f9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/438>.
>


—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
