### ISSUE TITLE
Unable to create a Test case when no dependency is created for the team 

### ISSUE THREAD

**Issue by chandanghosh21** [AutomationSolutionz/Framework_0.1#439]
URL: http://demo.automationsolutionz.com/Home/Login/

1. Go to the above URL
2. Login with valid credential
3. Try to create a test case

Please see the attachment.
![server not responding](https://cloud.githubusercontent.com/assets/11033216/6332325/c7a21b52-bbae-11e4-9f3a-c9caebb0999e.jpg)

Expected result: Test case should create
Actual Result: Unable to create a test case.

**Comment by aazizmojumdar** [comment]
I also fetch this issue.

**Comment by riz-hossain** [comment]
Thanks.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Md. Abdul Aziz MojumdarSent: Monday, February 23, 2015 12:40 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Unable to create a Test case  (#439)I also fetch this issue.

—Reply to this email directly or view it on GitHub.

**Comment by sazid** [comment]
When something fails or you find a bug, please try to attach the log file so that it instantly helps the developer to find the correct spot in the code (because, there's thousands of lines of code to look at).

**Comment by riz-hossain** [comment]
@minar 
@shetu 

What's happening here?

**Comment by riz-hossain** [comment]
Is it happening to all test cases? 

Provide all the details parameters you are using for this test case. 

List the steps you are using.

**Comment by riz-hossain** [comment]
@shetu 

Looks like there is no dependency created for this project. 

We need to handle this if someone doesn't want to have any dependencies.  

Aziz, Chandan. Please talk with Minar or Shetu to clarify what is dependency, why it is used and how it works for test case management.

**Comment by Taitalus** [comment]
So one test case might not have any dependencies right??

**Comment by riz-hossain** [comment]
That team and project may not have any dependencies and we need to be able create test cases and run. If someone creates a test case without dependencies and later adds dependency to their team, test cases should still run.   When test cases with dependencies and not dependency are selected together, we should not remove test cases that do not have dependencies.If no dependency is selected, we may want to give some kind of notification and link to the page to create dependency (needs more discussion, you can create a requirement for it for future with low priority) Minar: have a look at the step list in this project. Seems like it is getting steps from other projects (not sure). Getting steps from other team is okay but not other projects.  When no manual driver is created and a manual test step is created directly from the test case we can create a manual driver with the following formats: ManualTeamName Team name would be the current team they are logged in with.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Monday, February 23, 2015 10:25 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Unable to create a Test case  (#439)So one test case might not have any dependencies right?? 

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
‎Minar or Shetu please create a dependency for browser for time being and explain to Chandan and Aziz their functionality.  Make sure you can create test cases. Priority for this will be lower for time being as we need admin management page done first for our clients delivery.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: chandanghosh21Sent: Monday, February 23, 2015 11:54 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Unable to create a Test case  (#439)URL: http://demo.automationsolutionz.com/Home/Login/


Go to the above URL
Login with valid credential
Try to create a test case


Please see the attachment.


Expected result: Test case should create
Actual Result: Unable to create a test case.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Salam Guys,

When you log a new bug always add the tag Triage.  This is the tag Sunny
bhaie will use to assign task to appropriate developers.

Sunny bhaie please review all new bugs logged by our testers and follow up
with developers to identify which bug belongs to who and confirm with me
for priority.

All please follow this process immediately.



Thanks,
Riz

-- 

Riz Hossain
Engineering Physics (B.Eng)
Automation Test Lead
Research In Motion
295 Phillip Street
Waterloo, ON N2L 3L3


This transmission (including any attachments) may contain confidential
information, privileged material (including material protected by the
solicitor-client or other applicable privileges), or constitute non-public
information. Any use of this information by anyone other than the intended
recipient is prohibited. If you have received this transmission in error,
please immediately reply to the sender and delete this information from
your system. Use, dissemination, distribution, or reproduction of this
transmission by unintended recipients is not authorized and may be unlawful.

**Comment by riz-hossain** [comment]
body {  font-family: "Calibri","Slate Pro","sans-serif"; color:#262626 }  ‎Hi Minar, Please create automation accounts for Kumanan, Chandan, and Aziz.  Also add an additional account for Steve.Madden@automationsolutionz.comThanks,RizSent from my BlackBerry 10 smartphone on the TELUS network.

**Comment by riz-hossain** [comment]
Chandan vai and Aziz vai have their accounts now. So I need to create other
two?

On Tue, Feb 24, 2015 at 11:01 AM, Riz Hossain <hossain.iqbal@gmail.com>
wrote:

> ‎Hi Minar,
>
> Please create automation accounts for Kumanan, Chandan, and Aziz.
>
> Also add an additional account for Steve.Madden@automationsolutionz.com
>
> Thanks,
> Riz
>
> Sent from my BlackBerry 10 smartphone on the TELUS network.
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.

**Comment by riz-hossain** [comment]
Yes.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Tuesday, February 24, 2015 12:44 AMTo: Riz HossainCc: Raju Ahmed Shetu; Kumanan; chandanghosh21; Aziz TesterSubject: Re: Email accountsChandan vai and Aziz vai have their accounts now. So I need to create other two?On Tue, Feb 24, 2015 at 11:01 AM, Riz Hossain <hossain.iqbal@gmail.com> wrote:  ‎Hi Minar, Please create automation accounts for Kumanan, Chandan, and Aziz.  Also add an additional account for Steve.Madden@automationsolutionz.comThanks,RizSent from my BlackBerry 10 smartphone on the TELUS network.
-- Matiur Rahman MinarProgrammerAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.
