### ISSUE TITLE
features and section with sub options should be displayed with / or \ 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#442]
CourseSettings.Admin	User_Settings.Admin

The dots above should be replaced with slash.. see the view and organize page 

![image](https://cloud.githubusercontent.com/assets/5302523/6342990/2b0c905a-bbaf-11e4-8dc0-190936cd3cdd.png)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
