### ISSUE TITLE
There is no option to search by Comment in execution page and automation run needs to add comments as the failed reason

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#444]
As we fix the bug for common failed reason, user will need to search for common failed reason by comment.

This feature was there from day 1 but we somehow removed it.

first error message of the first failed step for automation run wiill be added in the comment of the step.

This is one of our highlight of demo and presentation.  This needs be back as soon as you are done with Admin page stuff

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
