### ISSUE TITLE
Project settings: I can create a type of dependency but i cannot add any new item to it

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#445]
This is the highest priority bug.  Before working on anything, fix this one ASAP.

**Comment by m3thun** [comment]
@riz-hossain Before I copied this over, can you please explain what the label "Release Gating" means? Thanks!

**Comment by m3thun** [comment]
@riz-hossain Copied and Closing!

**Comment by riz-hossain** [comment]
If it's release gating, that means without fixing this bug we can never release the product. It's similar to critical... but critical issue can be decided to descope... meaning, we can still remove the feature all together and release the product...Release gating would mean we cannot remove the feature to avoid the bug.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Thursday, August 27, 2015 8:07 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Project settings: I can create a type of dependency but i cannot add any new item to it (#445)@riz-hossain Before I copied this over, can you please explain what the label "Release Gating" means? Thanks!

—Reply to this email directly or view it on GitHub.
