### ISSUE TITLE
Create test case - Step should show "Step Title" 

### ISSUE THREAD

**Issue by chandanghosh21** [AutomationSolutionz/Framework_0.1#451]
URL: http://demo.automationsolutionz.com/Home/Login/

1. Go to the above Step
2. Login with valid credential
3. Click on TESTING Tab ---> Test Case ---> Create/Edit
4. Click on the 'Steps' tab
5. Observe the heading

Please see the attachment
![step_title](https://cloud.githubusercontent.com/assets/11033216/6366770/10b7bc10-bcf5-11e4-8437-993222ce2492.jpg)

Expected Result: "Step title" should show.
Actual Result: "Step" is showing

**Comment by riz-hossain** [comment]
Not going to change for now
