### ISSUE TITLE
Unable to Create Test Case for ( ' ' ) sign  

### ISSUE THREAD

**Issue by chandanghosh21** [AutomationSolutionz/Framework_0.1#452]
URL: http://demo.automationsolutionz.com/Home/Login/

1. Go to the above Step
2. Login with valid credential
3. Click on TESTING Tab ---> Test Case ---> Create/Edit
4. Try to create a test case with  content  ( ' ' ) and observe the result

**Comment by sazid** [comment]
Hmm, we're already aware of this though. This is SQL injection.

Needs attention @riz-hossain. I posted about this in the google groups
preciously. If someone's got some time, please take a look at it.

**Comment by riz-hossain** [comment]
Was there a bug logged for it.?

Any bug we find discuss must be logged or else it will never be addressed. 

We need to find all the characters that are not supported and block them as user types.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
