### ISSUE TITLE
View and organize should be renamed to "Folder View"

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#454]
View and organize is not what people are used to seeing.  

Change the link name to "Folder View"

**Comment by sazid** [comment]
Just did a quick fix from my phone. Check it out & close the issue.

**Comment by sazid** [comment]
6b2dbcc6ed

**Comment by riz-hossain** [comment]
Also any other ui (table title test case creation) Needs the change to section to folder                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Wednesday, February 25, 2015 1:14 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] View and organize should be renamed to "Folder View" (#454)Just did a quick fix from my phone. Check it out & close the issue.

On Thu, Feb 26, 2015, 12:03 AM Riz Hossain <notifications@github.com> wrote:

> Assigned #454
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/454> to
> @sazid <https://github.com/sazid>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/454#event-241901589>
> .
>


—Reply to this email directly or view it on GitHub.
