### ISSUE TITLE
Admin Page BaseTemplate

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#468]
A base template for the admin view is to be done. 
There will be 3 menu link right now.
Project
  Create,
  Edit
  List Project

User 
  Create/Edit,
  Link to Project
  List Project

This will be okay for now. don't miss to add all the styling that are already present right now. please do this one asap and let me know.

**Comment by minar09** [comment]
done!

On Thu, Mar 26, 2015 at 2:12 PM, Raju Ahmed Shetu <notifications@github.com>
wrote:

> Assigned #468
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/468> to
> @minar09 <https://github.com/minar09>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/468#event-265574674>
> .
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.
