### ISSUE TITLE
Manage folder will not have any contol other than view.  new div will allow you to manage folder

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#473]
create another div to manage folder 

create, rename, delete option will be there to manage the folders.  

no one has been able to fix the rename bug or lots of other bugs around that folder view

**Comment by sazid** [comment]
Assalamualaikum. The bugs are certainly not that super hard to fix, its
just that, no one's been able to put enough time in it.

**Comment by sazid** [comment]
In the main server, I can confirm that none of the features: `New Folder`, `Create`, `Rename`, `Delete`, etc. are working as expected. When I do any of the actions, it shows that it executed the action successfully but, nothing changes. Even a full refresh reveals no change.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
