### ISSUE TITLE
performance need to be improved for view folder and search test case page

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#479]
There must be something wrong with the query or the way we are doing this.  it takes over 6 seconds just to load 15 test cases. 

result page does a lot more data fetching and calculation and yet that works a lot faster.

we need to find out whats causing the hold up and decide if we want to remove or modify it

**Comment by riz-hossain** [comment]
Our target should be that we need to be able to load at least 100 test cases in less than 5 seconds.  We may remove some column based on performance.

@Taitalus  & @minar09  Why is result page loading so much faster compared to test case pages?  Result page needs a lot more data compared to test case.. and result page is more complex and requires a lot more calculation as well.  Maybe we need to follow the same procedure that we are doing in result page

Data for title and ID is needed.  We also need to do all of them for 10 test cases.  Make sure all test cases have at least 7 steps with data.

Test set page data is missing.

In Deployment Page:(for 5 entries)
Column        Total                    Avg
Type             0.592                 0.1184
Time             0.151                 0.0302
Section         0.145                  0.029
Feature         0.153                 0.0306
Status           0.177                  0.0354

In test case search page: (for 10 entries)
Column        Total                    Avg
Type            1.217                  0.1217
Time            0.312                  0.0312
Section        0.339                  0.0339
Status          0.296                  0.0296

In Folder View Page: (for 5 entries)
Column        Total                    Avg
Type             1.03                   0.206
Time             0.237                 0.0474
Section         0.243                 0.0486
Feature         0.33                    0.066
Status           0.327                 0.0654

**Comment by Taitalus** [comment]
improved a lot more I guess.
