### ISSUE TITLE
loading icon for all the pages that we display test cases 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#483]
We need to add loading icon (not loading page image) for any action that takes more than 2 seconds.

During pagination, run deployment, saving test cases, generating report, or any other places, we should always put overlay loading icon.  

icon:
http://jsfiddle.net/eys3d/741/
http://imgur.com/gallery/WDC3j18
http://codepen.io/scrapmac/pen/iKHun

reference:
http://www.jqueryscript.net/demo/jQuery-Plugin-For-Creating-Loading-Overlay-with-CSS3-Animations-waitMe/

**Comment by riz-hossain** [comment]
We can always shrink the gif image so that it doesnt take much loading time..
![oie_23234853jlqcpjho](https://cloud.githubusercontent.com/assets/5302523/7785862/69976c0e-0174-11e5-9206-d0981f2feb3e.gif)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
