### ISSUE TITLE
offline machine are showing in deployment detail tab and schedule run

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#484]
under detail tab machine name.. it is showing all the machines.  It is supposed to show only the "on line" machine.

Same applies for schedule run

**Comment by Taitalus** [comment]
previously the requirement was to show all the machine that were in the database.

**Comment by riz-hossain** [comment]
In available machine list yes. But when selecting the machine for run w need to show only machines that are available.

**Comment by Taitalus** [comment]
I guess we were showing that only.                                                                                                                                                                                                                                                                                                                                        Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Sunday, May 24, 2015 6:18 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] offline machine are showing in deployment detail tab and schedule run (#484)In available machine list yes. But when selecting the machine for run w need to show only machines that are available. 

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Yes. We used to. Something changed and now we show all.  Again, we should show all in available but not in detail.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, May 24, 2015 10:43 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] offline machine are showing in deployment detail tab and schedule run (#484)                                                                                      I guess we were showing that only.                                                                                                                                                                                                                                                                                                                                        Raju Ahmed ShetuSoftware DeveloperAutomation Solutionz1212 Countrystone Drive,Kitchener, N2N 3R4.                                                                                                                                                                                                                From: Riz HossainSent: Sunday, May 24, 2015 6:18 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Raju Ahmed ShetuSubject: Re: [Framework_0.1] offline machine are showing in deployment detail tab and schedule run (#484)In available machine list yes. But when selecting the machine for run w need to show only machines that are available. 

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
Yep. got it.

**Comment by Taitalus** [comment]
done.
