### ISSUE TITLE
Move "Project" settings out to Admin page

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#485]
Except "Schedule Run" everything should be moved to project settings.

Deployment should be changed to "Execute"

Schedule Run:
Testing > Execute > "Schedule Run" (Second item)
and current run page should be:
Testing > Execute > "Run Now"  (First item)

**Comment by Taitalus** [comment]
Done works.
1. put the schedule run and run test under the execute dropdown.
2. Move Manage Team, Setup Email link from project to the Project Setting dropdown.
3. Updated the url for the project change.
So if you are in url like this. 
/Home/PROJ-17/SetupEmail/
and you switched from 'PROJ-17' to 'PROJ-19' then it will update the url like this. 
/Home/PROJ-19/SetupEmail/
4. Moved project settings under dependency tab.

**Comment by riz-hossain** [comment]
you havent moved anything to admin page.  all the project related settings
should be moved to admin page...


all these three must be moved to admin page.
http://demo.automationsolutionz.com/Home/PROJ-21/ManageTeam/
http://demo.automationsolutionz.com/Home/PROJ-21/SetupEmail/
http://demo.automationsolutionz.com/Home/ManageProject/

On Thu, Jul 9, 2015 at 1:13 PM, Raju Ahmed Shetu <notifications@github.com>
wrote:

> Done works.
> 1. put the schedule run and run test under the execute dropdown.
> 2. Move Manage Team, Setup Email link from project to the Project Setting
> dropdown.
> 3. Updated the url for the project change.
> So if you are in url like this.
> /Home/PROJ-17/SetupEmail/
> and you switched from 'PROJ-17' to 'PROJ-19' then it will update the url
> like this.
> /Home/PROJ-19/SetupEmail/
> 4. Moved project settings under dependency tab.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/485#issuecomment-120075239>
> .
>



-- 

Riz Hossain
Engineering Physics (B.Eng)
Automation Test Lead
Research In Motion
295 Phillip Street
Waterloo, ON N2L 3L3


This transmission (including any attachments) may contain confidential
information, privileged material (including material protected by the
solicitor-client or other applicable privileges), or constitute non-public
information. Any use of this information by anyone other than the intended
recipient is prohibited. If you have received this transmission in error,
please immediately reply to the sender and delete this information from
your system. Use, dissemination, distribution, or reproduction of this
transmission by unintended recipients is not authorized and may be unlawful.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
