### ISSUE TITLE
Schedule run page should look same as normal run page

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#486]
should look like normal run pages.  It should only display test set name the way it is currently done.
instead of date picker it will have the schedule picker options and manage manual pc will be gone. 

under available pc for schedule run, only automation PC should show. 

![image](https://cloud.githubusercontent.com/assets/5302523/7786215/a5997262-018b-11e5-8a3e-ba4565360b3d.png)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
