### ISSUE TITLE
dependency are not showing correctly on manage manual machine (create/edit) 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#494]
all dependencies should be showing up on manual machine

**Comment by Taitalus** [comment]
can you please close that. ?? I have done it in the new way.

**Comment by riz-hossain** [comment]
Tag everything as done that's done. If anything you did but not tested, assign to Tarique.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Thursday, July 9, 2015 4:56 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] dependency are not showing correctly on manage manual machine (create/edit)  (#494)can you please close that. ?? I have done it in the new way.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
