### ISSUE TITLE
execute button should be visible but disabled until all the required items are fulfilled.

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#496]
Additionally  it should give notification like test case create about which fields are missing.

**Comment by Taitalus** [comment]
Done. But the button is not disabled from the beginning but it give notification if any required fields are missing.

**Comment by matariq** [comment]
This looks much better now!

**Comment by riz-hossain** [comment]
It's done yet :)Shetu us making it even a little better...                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Saturday, July 11, 2015 3:09 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] execute button should be visible but disabled until all the required items are fulfilled. (#496)This looks much better now!

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Shetu, please make sure the next button location is changed to top of the page inside the gray box. Same with back. Also change the text as we talked.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
