### ISSUE TITLE
Switching between projects always asks for default project.  

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#501]
Default should only be set by going to user's profile option.

**Comment by riz-hossain** [comment]
- this is an annoying bug and should not be there ...
only if default value is not save, we should do this prompt,  if default value exists, we shouldnt prompt

**Comment by Taitalus** [comment]
Actually what we had done there was..
several teams work in a projects. so when the project is changed then the default value for team is removed as that team might not be in the new project. For this reason it is kept.

**Comment by riz-hossain** [comment]
Default is different than just trying other projects When I set default it means no matter which proejct I had selected last, if I sign out and sign back in, I will see my default. If I just want to switch temporary, then I shouldnt have to change my default.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Monday, July 6, 2015 1:47 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Switching between projects always asks for default project.   (#501)Actually what we had done there was..
several teams work in a projects. so when the project is changed then the default value for team is removed as that team might not be in the new project. For this reason it is kept.

—Reply to this email directly or view it on GitHub.

**Comment by Taitalus** [comment]
Vai that is the way we have done this far, if we want to change it,it will be a long job.. okay??

**Comment by Taitalus** [comment]
@tariquesiddique check this.

**Comment by riz-hossain** [comment]
Please confirm and close

**Comment by matariq** [comment]
Verified
