### ISSUE TITLE
Testing->Deployment->Manage Manual Machine-Without branch I cannot create a Manual Machine

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#504]
- on manual machine i dont have any branch created.  i shouldnt have to create any branch if i dont want to.  Currently without creating any branch, i cannot create a manual machine.

**Comment by riz-hossain** [comment]
make sure all these bugs are solved quickly

**Comment by riz-hossain** [comment]
I couldn't create manual machine until I had branch and dependency created.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
