### ISSUE TITLE
Empty string dependency name was accepted.  

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#506]
User should not be allowed to enter empty string.

**Comment by riz-hossain** [comment]
there are still lots of bugs in this area.  make sure you fix all the other bugs as well.

when deleting an item it says there are two items, but doesnt list them in div below

**Comment by riz-hossain** [comment]
Please confirm and close

**Comment by matariq** [comment]
Verified - Dependency name cannot be empty now
