### ISSUE TITLE
for any fields that can create a new item should have a direct link icon.  

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#514]
Example, label is a field that you need to create to add a new one.. we need to have an icon beside it that will automatically take us to the create label view.  it should always open a new  browser tab or a rich pop up window where all the content would be shown...

this feature is important mainly because it will guide new users using our product.  also it will optimize the flow.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
