### ISSUE TITLE
Customized Execution Report with different filters and test cases list

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#53]

**Comment by m3thun** [comment]
@riz-hossain Ok so this the oldest "Highest Priority" Ticket. You closed this ticket as duplicate. But Minar reopened it on Jan 24th. Why?

**Comment by riz-hossain** [comment]
We went back and forth with the design on this to really optimize a lot of things.   This is on of the core part of the framework. :)This one is done and can be closed.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Wednesday, August 19, 2015 12:35 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Customized Execution Report with different filters and test cases list (#53)@riz-hossain Ok so this the oldest "Highest Priority" Ticket. You closed this ticket as duplicate. But Minar reopened it on Jan 24th. Why?

—Reply to this email directly or view it on GitHub.
