### ISSUE TITLE
Requirement -> Create/Edit -> Description - There is a text limitation

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#531]
Very interesting bug - took us a while to figure out what was going on.

If we put a lot of text in description - we are unable to save the requirement. So 2 closely related issues

1. Why is there a text limit? We should not have a limit
2. If there is limitation we should at least notify the user why

**Comment by riz-hossain** [comment]
By default in db we have to give a limit of char. I think we need to come up with a acceptable limit size for this.  Would having about 5 pages be enough?   And yes, we need to give a warning and feed back for anything of this type.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Saturday, July 11, 2015 1:36 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Requirement -> Create/Edit -> Description - There is a text limitation (#531)Very interesting bug - took us a while to figure out what was going on.

If we put a lot of text in description - we are unable to save the requirement. So 2 closely related issues


Why is there a text limit? We should not have a limit
If there is limitation we should at least notify the user why


—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
5 pages should be more than enough. right now i came across this with about 10 lines

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
