### ISSUE TITLE
Requirement -> Create/Edit -> Assignment - should there be a field for this?

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#532]
I think there should be...we should be able to assign requirement to another user

**Comment by riz-hossain** [comment]
The way we are looking at requirement is ask for what you want. Tasks will be eventually linked to the requirement. So a single requirement will have multiple tasks.  But every item should have an owner... a requirement in our world would probably own by the development team lead. The progress of requirement would however will be automated. It will depend on all the tasks that would be created under it. The status of the requirement would also be automated and would inherit from task Status...When all the tasks are completed it will be marked as completed.We spent a lot of time planning for requirement and tasks.   Minar has bee really busy with study and other test case related items.  But he will be switching to this full time in near future and at that time, he can talk with you to clear things out as well.                                                                                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Saturday, July 11, 2015 1:39 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Requirement -> Create/Edit -> Assignment - should there be a field for this? (#532)I think there should be...we should be able to assign requirement to another user

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
