### ISSUE TITLE
UI changes for linking components and the view

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#538]
for linked items,  we will have the exact same view as execution page of a runid
http://demo.automationsolutionz.com/Home/RunID/Sun-Jun-28-11:38:21-2015/

make sure pagination and display per page is added.  make sure search and filter options are there.

if you want to add/remove item, we will have the exact view as test set add/remove view.  there will be a button at the top right of the tab .. Add/Remove 

http://demo.automationsolutionz.com/Home/ManageSetTag/set/Regression%20Test%20Suite/

do this with a div .. so it doesn't go away to a new page.. so just that tab will switch to this view.

**Comment by minar09** [comment]
LInking UI for all components? in respective tabs?

**Comment by riz-hossain** [comment]
Yes. So if I am creating a task. I go to test case tab. Then I will see a filter bar and below that I will see all the test cases that are linked. If I want to remove or add.. I will click on add/remove. It will take me to test set add/remove page view. . When I click done... I should be back to Linked item view.  If I go to requirement tab, I will see related requirements and so on....                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Saturday, July 11, 2015 3:06 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] UI changes for linking components and the view (#538)LInking UI for all components? in respective tabs?

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
