### ISSUE TITLE
search view for req, task, and bug should be identical to test case search

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#539]
please follow identical format as test case search:

we will eventually change the way we do search ..we will change the search option as result page where we have the side drawer.... 

if you can do the side drawer that is better .. we can maybe change the test case search instead....

the main reason is with side drawer we can add additional features like saving default query .. or add the function to create "And" / "Or" query..... we will come back to this later..

for now please use the side drawer and keep everything same as test case search page (pagiination witih numbers, drop down to show how many items to show per page.. and copy/edit icon)

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
