### ISSUE TITLE
in test case search, i cannot search by label 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#540]
Minar, i cannnot search test cases on any search option... i hope its a single global function and you dont have to go to each ones ...if that is the case .. make sure execute and set pages are done first and then keep this ticket open until all the other ones are solved.

**Comment by minar09** [comment]
In which page ‎is it happening?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Riz HossainSent: Saturday, July 11, 2015 7:05 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Matiur Rahman MinarSubject: [Framework_0.1] in test case search, i cannot search by label  (#540)Minar, i cannnot search test cases on any search option... i hope its a single global function and you dont have to go to each ones ...if that is the case .. make sure execute and set pages are done first and then keep this ticket open until all the other ones are solved.

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
All the pages that we can search test cases.  Look at execute page and test set page first (add/remove)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Saturday, July 11, 2015 9:22 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] in test case search, i cannot search by label (#540)                                                                                      In which page ‎is it happening?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Riz HossainSent: Saturday, July 11, 2015 7:05 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Matiur Rahman MinarSubject: [Framework_0.1] in test case search, i cannot search by label  (#540)Minar, i cannnot search test cases on any search option... i hope its a single global function and you dont have to go to each ones ...if that is the case .. make sure execute and set pages are done first and then keep this ticket open until all the other ones are solved.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
