### ISSUE TITLE
By default all project and team should have Manual as driver 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#543]
I couldn't update test case because driver was not created. 

I thought we fixed this already. I think this needs to be done in a hard code in the framework. 

Or when a new team is created, we should be default create a driver called "Manual"

**Comment by minar09** [comment]
Shouldn't test step created on the fly using driver "Manual" rather than "webDriver"?

**Comment by riz-hossain** [comment]
yes

**Comment by m3thun** [comment]
@riz-hossain Minar has tagged it as "Done". Please verify and close the ticket.

**Comment by m3thun** [comment]
@riz-hossain Please confirm if it's DONE.

**Comment by riz-hossain** [comment]
Please assign it to Tarrique for verification...                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Tuesday, August 25, 2015 9:33 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] By default all project and team should have Manual as driver  (#543)@riz-hossain Please confirm if it's DONE.

—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
This seems to be working fine.

Works on a new project just created

**Comment by riz-hossain** [comment]
So when a new project and team is created, and you go to create a new test case and create a manual step on the fly from the test case create page, it automatically assisgns manual as the driver.. right?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Tuesday, August 25, 2015 9:44 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] By default all project and team should have Manual as driver  (#543)This seems to be working fine.

Works on a new project just created
On Aug 25, 2015 9:42 PM, "Riz Hossain" <notifications@github.com> wrote:

> Please assign it to Tarrique for verification...
> Sent from my BlackBerry 10 smartphone on the TELUS network. From:
> mithunSent: Tuesday, August 25, 2015 9:33 PMTo:
> AutomationSolutionz/Framework_0.1Reply To:
> AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re:
> [Framework_0.1] By default all project and team should have Manual as
> driver (#543)@riz-hossain Please confirm if it's DONE.
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/543#issuecomment-134787038>
> .
>


—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
