### ISSUE TITLE
Requirement -> Create/Edit - Milestone not showing in drop down menu

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#546]
Cannot create requirement as milestone not showing

**Comment by minar09** [comment]
Is there milestone created for that team and project?

**Comment by matariq** [comment]
Yes - Project: Network Testing and Team: Core Team - there is a milestone 'NWT: Pre - Demo'. This milestone is showing if I try to create a Task but not when creating Requirement

**Comment by minar09** [comment]
I can see milestone in my end, even in demo server logged as you.
![image](https://cloud.githubusercontent.com/assets/3684134/8666891/85935ad0-2a19-11e5-8afb-d952743ab138.png)

![image](https://cloud.githubusercontent.com/assets/3684134/8666921/c4e6bd9e-2a19-11e5-878d-e2e2123a19ea.png)

![image](https://cloud.githubusercontent.com/assets/3684134/8666900/9f24748e-2a19-11e5-8af6-36a390a49bad.png)

**Comment by riz-hossain** [comment]
This might be cash related issue. Please clean browser cash, and re-try.

**Comment by matariq** [comment]
Verified - working now. Needed to clear cache
