### ISSUE TITLE
Test case searched by label gives error after deployment

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#552]
also it does not show all test cases when a label is selected in test case search.

**Comment by riz-hossain** [comment]
This is a critical bug and needs to be fixed Asap

**Comment by Taitalus** [comment]
Found the bug. Minar you didn't save the label in test case tag table.all
my search for test cases are coming from the test case tag table. You label
is saving its linking with test cases in the label map.so please do change
the search function accordingly.

**Comment by riz-hossain** [comment]
Labels are generic now. Label goes to all components so they should be stored separately.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Tuesday, July 14, 2015 12:31 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Test case searched by label gives error after deployment (#552)Found the bug. Minar you didn't save the label in test case tag table.all
my search for test cases are coming from the test case tag table. You label
is saving its linking with test cases in the label map.so please do change
the search function accordingly.
On Jul 14, 2015 6:42 PM, "Riz Hossain" <notifications@github.com> wrote:

> This is a critical bug and needs to be fixed Asap
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/552#issuecomment-121228773>
> .
>


—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@Taitalus This highest priority bug is more than a month old. Please address this issue soon after your exam ends. Thanks!

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
