### ISSUE TITLE
Home Page Dashboard -> Requirements Chart typo

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#560]
Should be Requirements instead of 'Reuirements'

**Comment by riz-hossain** [comment]
Should be a quick fix... so please fix the spelling error

**Comment by m3thun** [comment]
@riz-hossain Please update the status this ticket. This one has both "Started" and "Done" tag.

**Comment by m3thun** [comment]
spelling has been fixed
