### ISSUE TITLE
Step data are not showing in step data tab 

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#567]
i think it broke after you add the step status changes.

if i go to an older project with older steps, i can see data...  under "Step Data"

its also not showing under execution page.

**Comment by m3thun** [comment]
@minar09 This high priority bug must be fixed asap! Please give an update on this. I could see you started working on it 5 days ago. Thanks!

**Comment by minar09** [comment]
I submitted fix for this too.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: mithunSent: Monday, August 17, 2015 6:26 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Matiur Rahman MinarSubject: Re: [Framework_0.1] Step data are not showing in step data tab (#567)@minar09 This high priority bug must be fixed asap! Please give an update on this. I could see you started working on it 5 days ago. Thanks!

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain Please verify the fix and close this ticket. Otherwise I'll have to copy it over to the new repo. Thanks!

**Comment by riz-hossain** [comment]
@Mithun please assign it to Tarrique                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Tuesday, August 25, 2015 9:21 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Step data are not showing in step data tab (#567)@riz-hossain Please verify the fix and close this ticket. Otherwise I'll have to copy it over to the new repo. Thanks!

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
