### ISSUE TITLE
"Atleast one verification point must be part of test case" Error when deleting step 

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#571]
Take Test Case with multiple steps and verification points

Delete Test Step from middle of test case

Save Test Case

Test Case gives above error although it has a verification point. - TC cannot be saved

This is not a cache related issue.

**Comment by riz-hossain** [comment]
If this is reproducible, then it becomes a critical issue.
@Taitalus make sure this is solved asap along with few other bugs you found on test case create.

**Comment by riz-hossain** [comment]
- Currently not reproducible

**Comment by riz-hossain** [comment]
steps to reprod
- Set VP as the last test case
- Edit the test case and remove any step above the last step that has the VP
- Try to Save

**Comment by m3thun** [comment]
@Taitalus What's the update on this, Shetu?

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
