### ISSUE TITLE
Re-run Test Case does NOT use new/updated test case steps

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#577]
Steps to reproduce:
- Create automated test case with one step (For example: Start Browser)
- Run Test Case
- Once execution finishes, go to test case and change step to a different step (For example: Start Chrome)
- Go to Testing->Run->Execute & select previous run of same test case
- Re-run test case

The initially configured test step (i.e Select Browser) is still used. A new test execution run needs to be defined for it to use the updated step (Start Chrome)

**Comment by riz-hossain** [comment]
This is by design.  We want to preserve re-run data that was used during the first run.  

Normally this is needed when you are developing test cases.  

When you are developing test cases it's best to run locale.  

Will explain in user manual.
