### ISSUE TITLE
404 Error when user changes a project

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#579]
Click on name right hand corner
Click on Team & Project
Change project

Page not found (404)
Request Method:	GET
Request URL:	http://demo.automationsolutionz.com/Home/User/PROJ-25/PROJ-25HPROJ-25oPROJ-25mPROJ-25ePROJ-25/PROJ-25UPROJ-25sPROJ-25ePROJ-25rPROJ-25/PROJ-25
Using the URLconf defined in WebServer.urls, Django tried these URL patterns, in this order:
^$
^Home/$
^Home/Dashboard/$
^Home/User/$
^GetProjectNameForTopBar/$
^Home/.*/GetProjectNameForTopBar/$
^Home/Contact/$
^Home/Contact/URL/(?P<url>.+)/$
^Home/FileUploader/$
^Home/FileUploadSuccess/(?P<success>.+)/$
^Home/UserInfo/UploadProfilePicture/$
^Home/UserInfo/ServeProfilePictureURL/$
^Home/RemoveProfilePicture/
^truncate_tables/$
^Home/select2/$
^Home/Login/$
^User_Login/$
^Home/Results/$
^Home/.*/GetResultAuto/$
^Home/.*/GetFilteredDataResult/$
^Home/RunID/(?P<Run_Id>[^/]*)/$
^Home/RunID/(?P<Run_Id>[^/]*)/PerformanceGraph/$
^Home/RunID/(?P<Run_Id>[^/]*)/LiveView/$
^Home/.*/RunID_New/$
^Home/ ^RunID/(?P<Run_Id>[^/]*)/TC/(?P<TC_Id>[^/]*)/Execute/$
^Home/ ^RunID/(?P<Run_Id>[^/]*)/TC/(?P<TC_Id>[^/]*)/View/$
^Home/ ^.*/AutoTestCasePass/$
^Home/ ^.*/specific_dependency_settings/$
^Home/ ^superAdminFunction/Project/$
^Home/ ^.*/Create_New_Project/$
^Home/ ^superAdminFunction/ListProject/$
^Home/ ^.*/GetProjectOwner/$
^Home/ ^superAdminFunction/AddUser/$
^Home/ ^superAdmin/$
^Home/ ^superAdminFunction/AssignMembers/$
^Home/ ^.*/Create_New_User/$
^Home/ ^superAdminFunction/ListUser/$
^Home/ ^superAdminFunction/User/(?P<user_id>[^/]+)/$
^Home/ ^superAdminFunction/Project/(?P<project_id>[^/]+)/$
^Home/ ^.*/ListProjects/$
^Home/ ^.*/Edit_User/$
^Home/ ^AssignTesters/$
^Home/ .*/get_projects/$
^Home/ .*/update_team_project/$
^Home/ .*/Edit_Project/$
^Home/.*/DataFetchForTestCases/$
^Home/.*/TestDataFetch/$
^Home/.*/UpdateData/$
^Home/.*/LogFetch/$
^Home/.*/ResultFilter/$
^Home/.*/GetPageCount/$
^Home/.*/RunIDStatus/$
^Home/.*/FilterDataForRunID/$
^Home/.*/AutoCompleteTag/$
^Home/RunID/$
^Home/.*/AutoCompleteTestCasesSearch/$
^Home/.*/AutoCompleteUsersSearch/$
^Home/.*/AutoCompleteEmailSearch/$
^Home/.*/AutoCompleteTesterSearch/$
^Home/.*/Table_Data_TestCases/$
^Home/.*/TableDataTestCasesOtherPages/$
^Home/.*/Table_Data_TestResult/$
^Home/.*/RunId_TestCases/$
^Home/.*/Update_RelatedItems/$
^Home/.*/FailStep_TestCases/$
^Home/.*/TestCase_TestSteps/$
^Home/.*/TestCase_TestSteps_SearchPage/$
^Home/.*/TestCase_Detail_Table/$
^Home/.*/TestStep_Detail_Table/$
^Home/.*/createTablefromString/$
^Home/ManageTestCases/$
^Home/ManageTestCases/getData/$
^Home/ManageTestCases/setData/createSection/$
^Home/ManageTestCases/setData/renameSection/$
^Home/ManageTestCases/setData/deleteSection/[^/]*$
^Home/ManageTestCases/CreateProductSections/$
^Home/ManageTestCases/CreateProductSections/ProductSectionsCreated/$
^Home/ManageTestCases/Create/[^/]*$
^Home/.*/Edit_TestCase$
^Home/ManageTestCases/Edit/AutoCompleteTagSearch/$
^Home/.*/AutoCompleteTestCasesSearchOtherPages/$
^Home/.*/AutoCompleteTestStepSearch/$
^Home/.*/GetProductSection/$
^Home/.*/GetProductFeature/$
^Home/ManageTestCases/CreateNewTestCase/$
^Home/ManageTestCases/CreateNew/(?P<tc_id>[^/]*)/$
^Home/ManageTestCases/Edit/(?P<tc_id>[^/]*)/$
^Home/.*/TestCase_EditData/$
^Home/ManageTestCases/SearchEdit/$
^Home/ManageTestCases/Create/AutoCompleteTagSearch/$
^Home/ManageTestCases/Create/AutoCompleteTestStepSearch/$
^Home/ManageTestCases/Create/Submit_New_TestCase/$
^Home/.*/Submit_New_TestCase/$
^Home/.*/GetSections/$
^Home/.*/GetFeatures/$
^Home/.*/GetBrowsers/$
^Home/.*/GetVersions/$
^Home/.*/GetTesters/$
^Home/.*/GetRunTypes/$
^Home/.*/GetStatus/$
^Home/.*/GetUsers/$
^Home/.*/GetMileStones/$
^Home/.*/GetMileStoneID/$
^Home/.*/GetMileStoneByID/$
^Home/EditMilestone/(?P<ms_id>[^/]*)/$
^Home/.*/MilestoneRequirements/$
^Home/.*/MilestoneTeams/$
^Home/.*/MilestoneTasks/$
^Home/.*/MilestoneBugs/$
^Home/.*/MilestoneTestings/$
^Home/.*/MilestoneReport/$
^Home/.*/Send_Report/$
^Home/.*/Auto_Step_Create/$
^Home/ManageTestCases/DeleteExisting/$
^Home/.*/DeleteTestCase/$
^Home/.*/GetStepNameType/$
^Home/.*/Go_TestCaseID/$
^Home/.*/Go_TestCaseStatus/$
^Home/.*/TestSet_Auto/$
^Home/.*/TestTag_Auto/$
^Home/.*/TestCase_Auto/$
^Home/ManageSetTag/$
^Home/.*/GetSetTag/$
^Home/ManageSetTag/(?P<type>[^/]*)/(?P<name>[^/]*)/$
^Home/ManageSetTag/(?P<type>[^/]*)/(?P<name>[^/]*)/EditOrder/$
^Home/.*/createNewSetTag/$
^Home/.*/DeleteSetTag/$
^Home/.*/AddTestCasesSetTag/$
^Home/.*/DeleteTestCasesSetTag/$
^Home/.*/UpdateSetTag/$
^Home/ManageTestCases/TestStep/$
^Home/ManageTestCases/CreateStep/$
^Home/ManageTestCases/CreateStep/Process_CreateStep/$
^Home/.*/TestStep_Auto/$
^Home/.*/TestFeature_Auto/$
^Home/.*/TestDriver_Auto/$
^Home/.*/GetFeature/$
^Home/.*/GetDriver/$
^Home/.*/TestFeatureDriver_Auto/$
^Home/.*/TestCase_Results/$
^Home/.*/TestSteps_Results/$
^Home/.*/Populate_info_div/$
^Home/.*/TestStep_Delete/$
^Home/.*/FeatureDriver_Delete/$
^Home/ManageTestCases/FeatureDriverDelete/$
^Home/ManageTestCases/TestStepDelete/$
^Home/ManageTestCases/Process_TestStep/$
^Home/ManageTestCases/Process_FeatureDriver/$
^Home/.*/TestStepAutoComplete/$
^Home/.*/TestStep_TestCases/$
^Home/.*/TestStepWithTypeInTable/$
^Home/CreateMilestone/$
^Home/ManageMilestone/$
^Home/RunTest/$
^Home/.*/AutoMileStone/$
^Home/.*/AutoCompleteMilestoneSearch/$
^Home/.*/MileStoneOperation/$
^Home/.*/Verify_Query/$
^Home/.*/Run_Test/$
^Home/.*/ReRun_Fail_TestCases/$
^Home/.*/Table_Data_UserList/$
^Home/.*/Auto_MachineName/$
Home/.*/CheckMachine/$
^Home/.*/AddManualTestMachine/$
^Home/.*/GetOS/$
^Home/.*/chartDraw/$
^Home/.*/ReRun/$
^Home/Performance/$
^Home/Performance/PerformanceResult/$
^Home/.*/Performance_ClickedBundle_Details_(?P<type>.)/$
^Home/DailyBuildResults/$
^Home/.*/Table_Data_DailyBuild/$
^Home/MKS-Report/$
^Home/.*/MKS_Report_Table/$
^Home/Analysis/$
^Home/.*/TestCaseSearch/$
^Home/.*/Selected_TestCaseID_Analaysis/$
^Home/.*/Selected_TestCaseID_History/$
^Home/ExecutionReport/$
^Home/.*/Execution_Report_Table/$
^Home/TestTypeStatus/$
^Home/TestTypeStatus/get?$
^Home/.*/TestTypeStatus_Report/$
^Home/BundleReport/$
^Home/BundleReport/get?$
^Home/.*/BundleReport_Table/$
^Home/.*/BundleReport_Table_Latest/$
^Home/.*/Bundle_Report/$
^Home/Documentation/$
^Home/Admin/$
^Home/.*/Process_Git/$
^Home/Driver/$
^Home/ManageStep/$
^Home/FeaDri/FeatureDriverOperation/$
^Home/FeaDri/FeatureDriverDelete/$
^Home/ManageTask/$
^Home/.*/Selected_TaskID_Analaysis/$
^Home/.*/FetchProject/$
^Home/ManageBug/$
^Home/CreateNewBug/$
^Home/.*/BugSearch/$
^Home/.*/Selected_BugID_Analaysis/$
^Home/EditBug/(?P<bug_id>[^/]*)/$
^Home/.*/LogNewBug/$
^Home/.*/Bugs_List/$
^Home/.*/ModifyBug/$
^Home/.*/BugOperation/$
^Home/ManageLabel/$
^Home/.*/CreateLabel/$
^Home/CreateNewLabel/$
^Home/ManageRequirement/$
^Home/(?P<project_id>[^/]*)/ManageTeam/$
^Home/.*/GetTesterManager/$
^Home/.*/Create_Team/$
^Home/.*/GetTeamInfo/$
^Home/(?P<project_id>[^/]*)/Team/(?P<team_name>[^/]*)/$
^Home/.*/Add_Members/$
^Home/.*/Delete_Members/$
^Home/.*/Delete_Team/$
^Home/.*/UpdateTeamName/$
^Home/ManageProject/$
^Home/Project/(?P<project_id>[^/]*)/$ [name='project_detail']
^Home/.*/Small_Project_Detail/$
^Home/.*/Get_Projects/$
^Home/.*/AddTeamtoProject/$
^Home/.*/SmallViewRequirements/$
^Home/.*/Reqs_List/$
^Home/(?P<project_id>[^/]*)/CreateNewRequirement/$
^Home/(?P<project_id>[^/]*)/getRequirements/$
^Home/(?P<project_id>[^/]*)/Requirements/(?P<req_id>[^/]*)/$ [name='detail_requirement']
^Home/Projects/(?P<project_id>[^/]*)/Requirements/(?P<team_id>[^/]*)/$
^Home/(?P<project_id>[^/]*)/Requirements/(?P<requirement_id>[^/]*)/post_comment/$
^Home/Project/(?P<project_id>[^/]*)/comment_post/$
^Home/Project/(?P<project_id>[^/]*)/comments/$ [name='comment_view']
^Home/ManageTestCases/SearchEdit-Dev/$
^Home/FeaDri/GetTestStepsAndTestCasesOnDriverValue/$
^Home/(?P<project_id>[^/]*)/CreateRequirement/[^/]*$
^Home/.*/SubmitCreateRequirement/$
^Home/(?P<project_id>[^/]*)/Task/[^/]*$
^Home/(?P<project_id>[^/]*)/CreateTask/[^/]*$
^Home/.*/Get_RequirementSections/$
^Home/.*/SubmitNewTask/$
^Home/.*/SubmitEditedTask/$
^Home/.*/SubmitChildTask/$
^Home/(?P<project_id>[^/]*)/EditTask/(?P<task_id>[^/]*)/$
^Home/(?P<project_id>[^/]*)/ChildTask/(?P<task_id>[^/]*)/$
^Home/.*/Tasks_List/$
^Home/.*/UpdateAccountInfo/$
^Home/.*/UpdateDefaultTeamForUser/$
^Home/.*/UpdateDefaultProjectForUser/$
^Home/Feature/$
^Home/.*/get_all_data_dependency_page/$
^Home/.*/add_new_dependency/$
^Home/.*/add_new_name_dependency/$
^Home/.*/get_all_name_under_dependency/$
^Home/.*/rename_dependency/$
^Home/.*/rename_driver/$
^Home/.*/add_new_version/$
^Home/.*/get_all_version_bit/$
^Home/.*/link_dependency/$
^Home/.*/unlink_dependency/$
^Home/.*/rename_name/$
^Home/.*/make_default_name/$
^Home/.*/add_new_branch/$
^Home/.*/get_all_version_under_branch/$
^Home/.*/add_new_version_branch/$
^Home/.*/rename_branch/$
^Home/.*/unlink_branch/$
^Home/.*/link_branch/$
^Home/.*/add_new_feature/$
^Home/.*/link_feature/$
^Home/.*/unlink_feature/$
^Home/.*/rename_feature/$
^Home/.*/get_all_first_level_sub_feature/$
^Home/.*/CreateLevelWiseFeature/$
^Home/.*/get_default_settings/$
^Home/Machine/(?P<machine_id>[^/]*)/$
^site_media/(?P<path>.*)$
^Home/.*/GetSubSections/$
^Home/.*/GetSubFeatures/$
^Home/(?P<project_id>[^/]*)/EditRequirement/(?P<req_id>[^/]*)/$
^Home/(?P<project_id>[^/]*)/ChildRequirement/(?P<req_id>[^/]*)/$
^Home/.*/Selected_Requirement_Analaysis/$
^Home/.*/SubmitEditRequirement/$
^Home/.*/SubmitChildRequirement/$
^Home/.*/AutoCompleteLabel/$
^Home/.*/AutoCompleteTask/$
^Home/.*/AutoCompleteRequirements/$
^Home/ViewMilestone/$
^Home/.*/New_Execution_Report/$
^Home/.*/get_all_machine/$
^Home/.*/Get_MileStone_Names/$
^Home/.*/Get_Feature_Path/$
^Home/.*/Check_Feature_Path/$
^Home/.*/SearchTestCase/$
^Home/RunHistory/(?P<tc_id>[^/]*)/$
^Home/ViewSteps/$
^Home/.*/Steps_List/$
^Home/.*/TestCaseDataFromMainDriver/$
^Home/.*/get_feature_path/$
^Home/User/ProfileDetail/$
^Home/ManageTestCases/EditStep/(?P<stepname>[^/]*)/$
^Home/.*/CreateEditStep/$
^Home/.*/TestStepSearch/$
^Home/.*/ViewAndOrganizeTestCases/$
^Home/.*/AutoCompleteTestCasesSearchTestSet/$
^Home/.*/get_run_objectives/$
^Home/uploadZip/$
^Home/.*/AutoCompleteObjectiveSearch/$
^Home/tc_file_upload/$
^Home/Cleanup/RunHistory/$
^Home/.*/get_cleanup_data/$
^Home/.*/cleanup_data/$
^Home/.*/delete_version/$
^Home/.*/rename_version/$
^Home/.*/add_new_driver/$
^Home/.*/link_driver/$
^Home/.*/link_team/$
^Home/ViewEditLabel/(?P<label_id>[^/]*)/$
^Home/.*/getLabelinfo/$
^Home/.*/EditLabel/$
^Home/.*/GetAllTeam/$
^Home/.*/ReorderSet/$
^Home/(?P<project_id>[^/]*)/ScheduleRun/$
^Home/(?P<project_id>[^/]*)/SetupEmail/$
^Home/.*/get_all_schedule_run/$
^Home/.*/AutoSetSearch/$
^Home/.*/enlist_schedule/$
^Home/.*/edit_schedule/$
^Home/.*/get_all_schedule_detail/$
^Home/.*/delete_schedule_run/$
^Home/(?P<project_id>[^/]*)/ScheduleRun/(?P<schedule_id>[^/]*)/$ [name='schedule_view']
^Home/.*/GetRelatedUrl/$
^Home/.*/updatemailingdetails/$
^Home/.*/getemaildetails/$
^Home/.*/delete_dependency_name/$
^Home/.*/delete_dependency/$
^Home/.*/TableDataDependencyTestCases/$
^Home/.*/FeatureUsageTestCase/$
^Home/.*/delete_feature/$
^Home/.*/delete_driver/$
^Home/.*/DriverUsageTestCase/$
^Home/.*/get_performance_type/$
^Home/.*/Get_graph_data/$
^Home/Help/$
^Home/.*/get_execution_log/$
^Home/TestStepType/$
^Home/TestStepType/get?$
^Home/.*/TestStepTypeStatus/$
^Home/.*/LabelSearch/$
^Home/.*/DeleteLabel/$
^Home/.*/Show_Labels/$
^Home/.*/Show_Milestones/$
^Home/.*/Get_Filtered_MileStone/$
^Home/.*/Show_Tasks/$
^Home/RunParameter/$
^Home/Version/$
^Home/.*/TestCases_PerLabel/$
^Home/.*/TestCases_PerTask/$
^Home/.*/AutoCompleteBugs/$
^Home/.*/Show_Reqs/$
^Home/.*/TestCases_PerRequirement/$
^Home/.*/CheckStepExistence/$
^Home/.*/Get_Filtered_Users/$
^Home/.*/Get_Filtered_Testers/$
^Home/.*/Show_Bugs/$
^Home/.*/RequirementSearch/$
^Home/.*/TaskSearch/$
^Home/.*/BugSearch_Drop/$
^Home/.*/MilestoneSearch/$
^Home/.*/CheckTestCaseExistence/$
^Home/.*/FilterDataForSet/$
^Home/.*/Get_Tasks/$
^Home/.*/Get_Bugs/$
^Home/.*/Get_AssignedTests/$
^Home/.*/GetRequirements/$
^Home/.*/AutoCompleteUserSearch/$
The current URL, Home/User/PROJ-25/PROJ-25HPROJ-25oPROJ-25mPROJ-25ePROJ-25/PROJ-25UPROJ-25sPROJ-25ePROJ-25rPROJ-25/PROJ-25, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by m3thun** [comment]
@riz-hossain Who should this bug be assigned to? Please also set the priority and deadline.

**Comment by m3thun** [comment]
@riz-hossain Please put labels this ticket.

**Comment by riz-hossain** [comment]
I didn't run into this issue while changing projects... Need more detail on this ticket...                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Wednesday, August 19, 2015 12:30 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] 404 Error when user changes a project (#579)@riz-hossain Please put labels this ticket.

—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
Closing do not see after updating db
