### ISSUE TITLE
Dashboard - Owned Requirements - Showing incorrect "Owned Requirements"

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#589]
Created new Project & User
View dashboard on first login
Requirements 175 should be 0

![image](https://cloud.githubusercontent.com/assets/13548066/9347380/dcf64488-45f6-11e5-8604-02a7c2ee68ac.png)

**Comment by m3thun** [comment]
@riz-hossain I'm labeling this to be a bug. Please label assignee and priority. I understand that the UI related matters are for Minar, but this should be for Shetu, am I right?

**Comment by adeelrehman007** [comment]
Not an issue. Closing.

**Comment by riz-hossain** [comment]
I like seeing these ones where you guys open and close right away :)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: AdeelSent: Tuesday, August 18, 2015 11:26 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Dashboard - Owned Requirements - Showing incorrect "Owned Requirements" (#589)Closed #589.

—Reply to this email directly or view it on GitHub.
