### ISSUE TITLE
Cannot delete Branch version #

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#590]
Cannot delete Beta

![image](https://cloud.githubusercontent.com/assets/13548066/9347472/ed505228-45f7-11e5-94fc-48a9a9b471ab.png)

**Comment by m3thun** [comment]
@riz-hossain Please label assignee and set priority.

**Comment by m3thun** [comment]
@riz-hossain Please let me know who should this be assigned to and also the priority level of this one. Thanks!

**Comment by riz-hossain** [comment]
@Taitalus  we should also add usage to it

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
