### ISSUE TITLE
Editing Milestone showing undefined suggestions

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#593]
![image](https://cloud.githubusercontent.com/assets/13548066/9347542/fe82bbfc-45f8-11e5-9189-55fff4cbf3b3.png)

**Comment by m3thun** [comment]
@riz-hossain Priority and Assignee pls!

**Comment by adeelrehman007** [comment]
Not an issue. Closing. db was out of date.
