### ISSUE TITLE
Cannot create Milestone with same name in another project

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#594]

**Comment by m3thun** [comment]
@riz-hossain Assignee and Priority pls!

**Comment by m3thun** [comment]
@riz-hossain You still haven't provided me with Priority level and Assignee info yet!

**Comment by riz-hossain** [comment]
@adeelrehman007 Can you please add what was observed when you tried to create a duplicate one?

**Comment by matariq** [comment]
There was no feedback response or any error msg

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
