### ISSUE TITLE
admin page doesnt need any password!!

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#597]
http://demo.automationsolutionz.com/Home/superAdmin/

i thought this was fixed!

@minar09 not sure if you can look into it as well... but this is critical issue...
@m3thun  this is critical but we will hold off this one until test case bugs are solved....

**Comment by m3thun** [comment]
@riz-hossain Noted!

**Comment by m3thun** [comment]
@riz-hossain As discussed over the phone, closing this issue. In fact, I'll delete it, so it doesn't stay even as a closed ticket.

**Comment by m3thun** [comment]
@riz-hossain so i guess u cant really delete a ticket, can u?

**Comment by riz-hossain** [comment]
I will be deleting the entire project ‎for various reasons.  As soon as we have moved over and all tickets are transferred                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Tuesday, August 25, 2015 9:08 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] admin page doesnt need any password!! (#597)@riz-hossain so i guess u cant really delete a ticket, can u?

—Reply to this email directly or view it on GitHub.
