### ISSUE TITLE
Following error received when renaming folder: "Same Folder name exists"

### ISSUE THREAD

**Issue by adeelrehman007** [AutomationSolutionz/Framework_0.1#605]
- Testing->Test Case->Folder View
- Click on New Folder, name Folder 'Files Seciton' and click OK
- Right click on folder and click Rename Folder
- Change name to 'Files Section' and click OK

Error received as shown in screenshot below. Issue always seems to occur when the folder name has two words and the first word isn't changed during renaming. 

![image](https://cloud.githubusercontent.com/assets/13548066/9456052/a24c5cf6-4aa0-11e5-8145-e3383eb8c18c.png)

**Comment by m3thun** [comment]
@riz-hossain copied to the new private repo.. closing here
